# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pikturit.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(175, 210)
        MainWindow.setMinimumSize(QtCore.QSize(175, 210))
        MainWindow.setMaximumSize(QtCore.QSize(175, 210))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grpBox = QtWidgets.QGroupBox(self.centralwidget)
        self.grpBox.setGeometry(QtCore.QRect(10, 10, 150, 181))
        self.grpBox.setObjectName("grpBox")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.grpBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 105, 100, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.grpBox)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(30, 45, 100, 20))
        self.lineEdit.setInputMask("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.grpBox)
        self.label_2.setGeometry(QtCore.QRect(30, 75, 100, 20))
        self.label_2.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.grpBox)
        self.label.setGeometry(QtCore.QRect(30, 15, 100, 20))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.grpBox)
        self.pushButton.setGeometry(QtCore.QRect(45, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.grpBox.setTitle(_translate("MainWindow", "Change Dimensions"))
        self.lineEdit.setText(_translate("MainWindow", "50x30"))
        self.label_2.setText(_translate("MainWindow", "New Dimensions"))
        self.label.setText(_translate("MainWindow", "Current Dimensions"))
        self.pushButton.setText(_translate("MainWindow", "Change"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec())
